#!/usr/bin/env python3
# Rasterize images/vx.svg to a high-res, alpha-aware Gaussian-blurred RGBA
# bitmap and emit it as a C header (raw RGBA bytes) for the viewer to upload
# straight to a GL texture. No runtime image decoder needed.
#
#   python scratch/gen_watermark.py
#
# Regenerate whenever vx.svg changes.
import io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG  = os.path.join(ROOT, "images", "vx.svg")
PNG  = os.path.join(ROOT, "images", "vx_watermark.png")
HDR  = os.path.join(ROOT, "src", "viewer", "EmbeddedWatermark.h")

HEIGHT = 1440         # source raster height (crisp up to ~4K; downscales cleanly)
BLUR   = 2.0          # Gaussian blur radius (px), per spec

import cairosvg
from PIL import Image, ImageFilter

png = cairosvg.svg2png(url=SVG, output_height=HEIGHT)
img = Image.open(io.BytesIO(png)).convert("RGBA")

# Alpha-aware (premultiplied) blur so transparent-black background does not
# bleed a dark fringe into the anti-aliased/blurred logo edges. Original RGB
# colours (white + #E5E5E5) are preserved; only the alpha shape softens.
try:
    import numpy as np
    a = np.asarray(img).astype(np.float32) / 255.0
    alpha = a[..., 3:4]
    pm = np.concatenate([a[..., :3] * alpha, alpha], axis=-1)
    pm_img = Image.fromarray((pm * 255.0 + 0.5).astype("uint8"), "RGBA") \
                  .filter(ImageFilter.GaussianBlur(BLUR))
    b = np.asarray(pm_img).astype(np.float32) / 255.0
    ba = np.clip(b[..., 3:4], 1e-4, 1.0)
    rgb = np.clip(b[..., :3] / ba, 0.0, 1.0)
    out = np.concatenate([rgb, b[..., 3:4]], axis=-1)
    final = Image.fromarray((out * 255.0 + 0.5).astype("uint8"), "RGBA")
    print("blur: alpha-aware (numpy)")
except Exception as e:
    print("blur: simple fallback (%s)" % e)
    final = img.filter(ImageFilter.GaussianBlur(BLUR))

final.save(PNG)
W, H = final.size

# RLE-compress the RGBA so a high-res watermark stays a small header. Each pixel
# is a little-endian uint32 (byte order R,G,B,A -> matches GL_RGBA/UNSIGNED_BYTE).
# The logo is mostly flat white + transparent, so run-length shrinks it hugely.
import numpy as np
arr = np.frombuffer(final.tobytes(), dtype="<u4")   # W*H pixels, R|G<<8|B<<16|A<<24
n = arr.size
# run boundaries: where consecutive pixels differ
change = np.nonzero(np.diff(arr))[0] + 1
starts = np.concatenate(([0], change))
ends   = np.concatenate((change, [n]))
counts = (ends - starts).astype(np.uint64)
values = arr[starts]

with open(HDR, "w", newline="\n") as f:
    f.write("#pragma once\n")
    f.write("// Auto-generated by scratch/gen_watermark.py from images/vx.svg.\n")
    f.write("// High-res, alpha-aware 2px-blurred brand watermark, RLE-compressed as\n")
    f.write("// (count, pixel) uint32 pairs; pixel is little-endian RGBA. Decoded once\n")
    f.write("// at startup and uploaded to a GL texture. Original logo colours kept.\n")
    f.write("#include <cstddef>\n")
    f.write("namespace pf {\n")
    f.write("inline constexpr int kVxWatermarkW = %d;\n" % W)
    f.write("inline constexpr int kVxWatermarkH = %d;\n" % H)
    f.write("inline const unsigned int kVxWatermarkRLE[] = {\n")
    line = []
    for cnt, val in zip(counts.tolist(), values.tolist()):
        line.append("%d,0x%08Xu" % (cnt, val))
        if len(line) == 8:
            f.write(",".join(line) + ",\n")
            line = []
    if line:
        f.write(",".join(line) + ",\n")
    f.write("};\n")
    f.write("inline constexpr size_t kVxWatermarkRLELen = sizeof(kVxWatermarkRLE)/sizeof(unsigned int);\n")
    f.write("} // namespace pf\n")

print("wrote %s  (%dx%d, %d runs, %.1f KB raw, header %.1f KB)"
      % (HDR, W, H, len(counts), W * H * 4 / 1024.0, os.path.getsize(HDR) / 1024.0))
