#include "io/FbxWriter.h"

#include <cstdio>
#include <fstream>
#include <iomanip>
#include <sstream>

namespace pf {

namespace {

// FBX object ids must be unique int64 handles; a fixed base + counter is fine
// for a freshly generated file (no external references to collide with).
constexpr int64_t kIdBase = 1000000;

std::string fbxEscape(const std::string& s) {
    // FBX ASCII strings are double-quoted; there is no escape for an embedded
    // quote, so replace it (and control chars) rather than emit invalid syntax.
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '"') out += '\'';
        else if ((unsigned char)c < 0x20) out += '_';
        else out += c;
    }
    return out;
}

} // namespace

void FbxWriter::beginCloud(const std::string& name,
                           const Vec3d& nodeTranslation,
                           const Vec3d& vertexOrigin) {
    Cloud c;
    c.name = name;
    c.translation[0] = nodeTranslation.x;
    c.translation[1] = nodeTranslation.y;
    c.translation[2] = nodeTranslation.z;
    c.vertexOrigin = vertexOrigin;
    clouds_.push_back(std::move(c));
}

void FbxWriter::addPoint(const Vec3d& worldPos,
                         uint8_t r, uint8_t g, uint8_t b,
                         uint16_t /*intensity*/, uint8_t /*classification*/) {
    if (clouds_.empty()) return;
    Cloud& c = clouds_.back();
    const Vec3d local = worldPos - c.vertexOrigin;
    c.verts.push_back(local.x);
    c.verts.push_back(local.y);
    c.verts.push_back(local.z);
    c.cols.push_back(r / 255.0f);
    c.cols.push_back(g / 255.0f);
    c.cols.push_back(b / 255.0f);
    ++c.count;
}

void FbxWriter::addSplat(const GaussianSplat& s) {
    if (clouds_.empty()) return;
    Cloud& c = clouds_.back();
    const Vec3d local = s.position - c.vertexOrigin;
    c.verts.push_back(local.x);
    c.verts.push_back(local.y);
    c.verts.push_back(local.z);
    // Diffuse colour is already in [0,1].
    auto clamp01 = [](float v) { return v < 0.0f ? 0.0f : (v > 1.0f ? 1.0f : v); };
    c.cols.push_back(clamp01(s.color[0]));
    c.cols.push_back(clamp01(s.color[1]));
    c.cols.push_back(clamp01(s.color[2]));
    ++c.count;
}

uint64_t FbxWriter::totalPrimitives() const {
    uint64_t n = 0;
    for (const Cloud& c : clouds_) n += c.count;
    return n;
}

bool FbxWriter::finish(const std::string& path, const Options& opts) {
    error_.clear();
    if (totalPrimitives() == 0) {
        error_ = "nothing to export (no points)";
        return false;
    }

    // Drop empty clouds so Definitions counts and Connections stay consistent.
    std::vector<const Cloud*> live;
    for (const Cloud& c : clouds_) if (c.count > 0) live.push_back(&c);
    if (live.empty()) {
        error_ = "nothing to export (all clouds empty after filtering)";
        return false;
    }

    std::ofstream out(path, std::ios::out | std::ios::trunc);
    if (!out) {
        error_ = "could not open output file: " + path;
        return false;
    }
    out << std::setprecision(6) << std::fixed;

    // ---- header --------------------------------------------------------------
    out << "; FBX 7.4.0 project file\n";
    out << "; Generated by " << opts.creator << "\n";
    if (!opts.sourceName.empty()) out << "; Source: " << fbxEscape(opts.sourceName) << "\n";
    out << "; ------------------------------------------------------\n\n";

    out << "FBXHeaderExtension:  {\n";
    out << "\tFBXHeaderVersion: 1003\n";
    out << "\tFBXVersion: 7400\n";
    out << "\tCreator: \"" << fbxEscape(opts.creator) << "\"\n";
    out << "}\n";

    // ---- global settings (axis + units) --------------------------------------
    // Vertices are baked to Y-up when opts.yUp; otherwise kept source Z-up.
    const int upAxis   = opts.yUp ? 1 : 2;          // 1 = Y, 2 = Z
    const int frontAxis = opts.yUp ? 2 : 1;         // remaining horizontal-ish axis
    out << "GlobalSettings:  {\n";
    out << "\tVersion: 1000\n";
    out << "\tProperties70:  {\n";
    out << "\t\tP: \"UpAxis\", \"int\", \"Integer\", \"\"," << upAxis << "\n";
    out << "\t\tP: \"UpAxisSign\", \"int\", \"Integer\", \"\",1\n";
    out << "\t\tP: \"FrontAxis\", \"int\", \"Integer\", \"\"," << frontAxis << "\n";
    out << "\t\tP: \"FrontAxisSign\", \"int\", \"Integer\", \"\",1\n";
    out << "\t\tP: \"CoordAxis\", \"int\", \"Integer\", \"\",0\n";
    out << "\t\tP: \"CoordAxisSign\", \"int\", \"Integer\", \"\",1\n";
    out << "\t\tP: \"UnitScaleFactor\", \"double\", \"Number\", \"\"," << opts.unitScaleCm << "\n";
    out << "\t}\n";
    out << "}\n";

    // ---- definitions ---------------------------------------------------------
    const size_t nClouds = live.size();
    out << "Definitions:  {\n";
    out << "\tVersion: 100\n";
    out << "\tCount: " << (nClouds * 2 + 1) << "\n";
    out << "\tObjectType: \"GlobalSettings\" {\n\t\tCount: 1\n\t}\n";
    out << "\tObjectType: \"Geometry\" {\n\t\tCount: " << nClouds << "\n\t}\n";
    out << "\tObjectType: \"Model\" {\n\t\tCount: " << nClouds << "\n\t}\n";
    out << "}\n";

    // ---- objects -------------------------------------------------------------
    out << "Objects:  {\n";
    int64_t id = kIdBase;
    std::vector<std::pair<int64_t, int64_t>> conns;  // (geomId, modelId)

    for (const Cloud* cp : live) {
        const Cloud& c = *cp;
        const int64_t geomId = id++;
        const int64_t modelId = id++;
        conns.emplace_back(geomId, modelId);

        // Geometry (control points + per-point colour).
        out << "\tGeometry: " << geomId << ", \"Geometry::" << fbxEscape(c.name)
            << "\", \"Mesh\" {\n";
        out << "\t\tVertices: *" << c.verts.size() << " {\n\t\t\ta: ";
        for (size_t i = 0; i < c.verts.size(); ++i) {
            if (i) out << ',';
            double v = c.verts[i];
            if (opts.yUp) {
                // (x,y,z) Z-up -> (x, z, -y) Y-up, baked per component triple.
                const size_t comp = i % 3;
                const size_t base = i - comp;
                if (comp == 1) v = c.verts[base + 2];
                else if (comp == 2) v = -c.verts[base + 1];
            }
            out << v;
        }
        out << "\n\t\t}\n";
        out << "\t\tGeometryVersion: 124\n";
        out << "\t\tLayerElementColor: 0 {\n";
        out << "\t\t\tVersion: 101\n";
        out << "\t\t\tName: \"Col\"\n";
        out << "\t\t\tMappingInformationType: \"ByControlPoint\"\n";
        out << "\t\t\tReferenceInformationType: \"Direct\"\n";
        out << "\t\t\tColors: *" << (c.count * 4) << " {\n\t\t\t\ta: ";
        for (uint64_t p = 0; p < c.count; ++p) {
            if (p) out << ',';
            out << c.cols[p * 3 + 0] << ',' << c.cols[p * 3 + 1] << ','
                << c.cols[p * 3 + 2] << ",1";
        }
        out << "\n\t\t\t}\n";
        out << "\t\t\tColorIndex: *0 {\n\t\t\t}\n";
        out << "\t\t}\n";
        out << "\t\tLayer: 0 {\n";
        out << "\t\t\tVersion: 100\n";
        out << "\t\t\tLayerElement:  {\n";
        out << "\t\t\t\tType: \"LayerElementColor\"\n";
        out << "\t\t\t\tTypedIndex: 0\n";
        out << "\t\t\t}\n";
        out << "\t\t}\n";
        out << "\t}\n";

        // Model (translation + true origin as a user property).
        out << "\tModel: " << modelId << ", \"Model::" << fbxEscape(c.name)
            << "\", \"Mesh\" {\n";
        out << "\t\tVersion: 232\n";
        out << "\t\tProperties70:  {\n";
        out << "\t\t\tP: \"Lcl Translation\", \"Lcl Translation\", \"\", \"A\","
            << c.translation[0] << ',' << c.translation[1] << ',' << c.translation[2] << "\n";
        out << "\t\t\tP: \"PF_WorldOrigin\", \"Vector3D\", \"Vector\", \"\","
            << opts.origin.x << ',' << opts.origin.y << ',' << opts.origin.z << "\n";
        out << "\t\t}\n";
        out << "\t\tShading: T\n";
        out << "\t\tCulling: \"CullingOff\"\n";
        out << "\t}\n";
    }
    out << "}\n";

    // ---- connections ---------------------------------------------------------
    out << "Connections:  {\n";
    for (const auto& c : conns) {
        out << "\tC: \"OO\"," << c.first << ',' << c.second << "\n";   // Geometry -> Model
        out << "\tC: \"OO\"," << c.second << ",0\n";                    // Model -> root
    }
    out << "}\n";

    out.flush();
    if (!out.good()) {
        error_ = "failed while writing output file: " + path;
        return false;
    }
    return true;
}

} // namespace pf
