# bump_version.cmake - Stamps this build with the version in VERSION, then
# increments the patch number for the *next* build. Runs on every build
# (attached to an ALL custom target, same pattern as web_build in
# CMakeLists.txt) so ViitorXPCViewer.exe always carries a fresh "1.0.<N>"
# build number, starting at 1.0.0 for the first build.
#
# VERSION file at the repo root holds the persisted MAJOR.MINOR.PATCH; only
# PATCH is bumped automatically. Bump MAJOR/MINOR by hand for real releases.

if(NOT DEFINED VERSION_FILE)
    set(VERSION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/VERSION")
endif()
if(NOT DEFINED OUTPUT_HEADER)
    set(OUTPUT_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/src/viewer/Version.h")
endif()

# Version stamped into THIS build (defaults to 1.0.0 if VERSION is missing or malformed).
set(PF_VERSION "1.0.0")
if(EXISTS "${VERSION_FILE}")
    file(STRINGS "${VERSION_FILE}" PF_VERSION_READ LIMIT_COUNT 1)
    string(STRIP "${PF_VERSION_READ}" PF_VERSION_READ)
    if(PF_VERSION_READ MATCHES "^[0-9]+\\.[0-9]+\\.[0-9]+$")
        set(PF_VERSION "${PF_VERSION_READ}")
    endif()
endif()

string(REPLACE "." ";" PF_VERSION_PARTS "${PF_VERSION}")
list(GET PF_VERSION_PARTS 0 PF_VERSION_MAJOR)
list(GET PF_VERSION_PARTS 1 PF_VERSION_MINOR)
list(GET PF_VERSION_PARTS 2 PF_VERSION_PATCH)

file(WRITE "${OUTPUT_HEADER}" "// Auto-generated by tools/bump_version.cmake — do not edit; edit VERSION instead.\n#pragma once\n\n#define PF_VERSION_MAJOR ${PF_VERSION_MAJOR}\n#define PF_VERSION_MINOR ${PF_VERSION_MINOR}\n#define PF_VERSION_PATCH ${PF_VERSION_PATCH}\n#define PF_VERSION_STRING \"${PF_VERSION}\"\n")

# Persist the NEXT build's version (patch + 1) so the following build picks it up.
math(EXPR PF_VERSION_NEXT_PATCH "${PF_VERSION_PATCH} + 1")
file(WRITE "${VERSION_FILE}" "${PF_VERSION_MAJOR}.${PF_VERSION_MINOR}.${PF_VERSION_NEXT_PATCH}\n")

message(STATUS "ViitorXPC build version: ${PF_VERSION} (next build: ${PF_VERSION_MAJOR}.${PF_VERSION_MINOR}.${PF_VERSION_NEXT_PATCH})")
